API_KEY = '77859.UuGjfAcRS8AFt5JpLRCJs7eWkLn7azw53dpjOCbH'
URL = 'http://api.vajehyab.com/v3/search'

db_names = ['dehkhoda: لغت‌نامهٔ دهخدا',
            'moein: فرهنگ فارسی معین',
            'amid: فرهنگ فارسی عمید',
            'motaradef: واژگان مترادف و متضاد',
            'farhangestan: فرهنگ واژه‌های مصوّب فرهنگستان',
            'sareh: واژه‌های فارسی سره',
            'ganjvajeh: فرهنگ گنجواژه',
            'wiki: واژه‌نامهٔ آزاد',
            'slang: اصطلاحات عامیانه',
            'quran: فرهنگ واژگان قرآن',
            'name: فرهنگ نام‌ها',
            'thesis: فرهنگ لغات علمی',
            'isfahani: لهجه و گویش اصفهانی',
            'bakhtiari: لهجه و گویش بختیاری',
            'tehrani: لهجه و گویش تهرانی',
            'dezfuli: لهجه و گویش دزفولی',
            'gonabadi: لهجه و گویش گنابادی',
            'mazani: لهجه و گویش مازنی',
            'en2fa: دیکشنری انگلیسی به فارسی',
            'ar2fa: دیکشنری عربی به فارسی',
            'fa2en: دیکشنری فارسی به انگلیسی',
            'fa2ar: دیکشنری فارسی به عربی']
